# Generated by Django 5.2.1 on 2025-06-04 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_offerletterdoument_alter_offerletter_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='student',
        ),
        migrations.AddField(
            model_name='offerletter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
